// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FinancialAPI.Models;

namespace FinancialAPI.Data
{
    public partial class FinancialModelContext : DbContext
    {
        public FinancialModelContext()
        {
        }

        public FinancialModelContext(DbContextOptions<FinancialModelContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Security> Securities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Security>(entity =>
            {
                entity.Property(e => e.SecurityDate).HasColumnType("datetime");

                entity.Property(e => e.SecurityName)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.SecurityPrice).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.SecurityTicker)
                    .HasMaxLength(255)
                    .IsUnicode(false);

            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}