// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialAPI.Models
{
    public partial class HistoricalSector
    {
        public int ID { get; set; }
        public decimal SectorMovement { get; set; }
        public DateTime DateCalculated { get; set; }
        public int? SectorID { get; set; }

        public virtual Sector Sector { get; set; }
    }
}