// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialAPI.Models
{
    public partial class HistoricalSecurity
    {
        public int ID { get; set; }
        public decimal SecurityMovement { get; set; }
        public DateTime DateCalculated { get; set; }
        public int? SecurityID { get; set; }

        public virtual Security Security { get; set; }
    }
}