// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialAPI.Models
{
    public partial class Sector
    {
        public Sector()
        {
            Securities = new HashSet<Security>();
        }

        public int ID { get; set; }
        public string SectorName { get; set; }

        public virtual ICollection<Security> Securities { get; set; }
    }
}