// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace FinancialAPI.Models
{
    public partial class Sector
    {

        public int ID { get; set; }
        public string SectorName { get; set; }

    }
}