// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinancialAPI.Models
{
    public partial class Security
    {
        public int ID { get; set; }
        public string SecurityName { get; set; }
        public string SecurityTicker { get; set; }
        public int SecuritySector { get; set; }
        public decimal SecurityPrice { get; set; }
        public DateTime? SecurityDate { get; set; }
        public int? SectorID { get; set; }

        public virtual Sector Sector { get; set; }
    }
}